project_id = "trvttgnjqlgbjknklnxo"

[functions.bot-chat]
verify_jwt = false

[functions.agent-builder]
verify_jwt = false

[functions.create-wallet]
verify_jwt = false

[functions.deploy-to-runpod]
verify_jwt = false

[functions.run-agent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.purchase-credits]
verify_jwt = false

[functions.verify-credits-payment]
verify_jwt = false

[functions.purchase-template]
verify_jwt = false

[functions.mint-agent-nft]
verify_jwt = false

[functions.social-api]
verify_jwt = false

[functions.verify-bot]
verify_jwt = false

[functions.start-trial]
verify_jwt = false

[functions.batch-register-bots]
verify_jwt = false

[functions.admin-api]
verify_jwt = false

[functions.daily-profit-email]
verify_jwt = false

[functions.github-build]
verify_jwt = false
